@startuml BibliotecaVirtual

left to right direction

actor Usuario as "Usuário" <<Geral>>
actor UsuarioComum as "Usuário Comum" <<Cliente>>
actor Administrador as "Administrador" <<Funcionário>>

Usuario <|-- UsuarioComum
Usuario <|-- Administrador

package "Biblioteca Virtual" {
    usecase "RF001 - Manter Livros" as UC1
    usecase "RF002 - Buscar Livros" as UC2
    usecase "RF002.1 - Visualizar detalhes de livros" as UC2_1
    usecase "RF003 - Registrar Empréstimo" as emprestimo
    usecase "RF004 - Atualizar estoque" as atualizar_estoque
    usecase "RF005 - Gerar Multa" as UC5
    ' usecase "RF005.1 - Enviar lembrete de devolução" as UC5_1
    usecase "RF006 - Autenticação no Sistema" as UC6
    usecase "RF007 - Gerar Relatórios" as UC7
    usecase "RF008 - Recomendar Livros" as recomendar
    usecase "RF009 - Enviar lembrete de devolução" as lembrete
    usecase "RF009.1 - Enviar notificação de multa" as notificacao_multa
    usecase "RF010 - Manter usuários" as UC10
    usecase "RF011 - Devolver Livro" as devolver
    usecase "RF012 - Definir Prazo" as UC12
    usecase "RF013 - Consultar Estoque" as UC13

    note right of UC2
        Busca por:
        - Título
        - Autor
        - Gênero
        - ISBN
    end note

    note bottom of lembrete
        Tipos:
        - Lembretes de devolução
        - Alertas de multas
        - Confirmações de empréstimo/devolução
    end note
}

Usuario --> UC2
Usuario --> UC2_1
Usuario --> emprestimo
Usuario --> UC6
Usuario --> devolver

Administrador --> UC1
Administrador --> UC7
Administrador --> UC10

emprestimo .> atualizar_estoque : include
emprestimo .> recomendar : extends
note on link #LightBlue
   Recomendar livros com base no histórico e avaliações
end note

emprestimo .> lembrete : include (após empréstimo)
emprestimo .> UC12 : include
emprestimo .> UC13 : include
UC5 .> notificacao_multa : include (multa aplicada)
devolver .> atualizar_estoque : include

devolver <.. UC5 : extends
note on link #red: Em caso de atraso

note right of Administrador
    Herda todas as operações de Usuário
end note

@enduml