@startuml API Backend

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(api, "API Backend", "Spring boot", "Armazena lógica do programa e gerencia interações com o banco de dados") {
    Component(control, "Rest Controller", "Controller Spring MVC", "Recebe requisições HTTP")
    Component(service, "Service", "Classes de Serviço", "Contém lógica de negócio (validações para persistência, converter DTOs, etc)")
    Component(repository, "Repository", "Interface JPA", "Gerencia operações de banco de dados")
}

Rel(control, service, "Chama métodos")
Rel(service, repository, "Consulta DB")

@enduml